syntax = "proto3";
package messages.transport.v1;

import "airis/telemetry/v1/telemetry.proto";

/*
 * This file defines internal transport protocols for communications between
 * the central control server and client peripherals (SDRs, web clients)
 */

// Server response to node creation to establish PUB/SUB link with client
message EstablishClient {
  string msg = 1;
}

message Message {
  string heading = 1;
  string message = 2;
}

message PointingCmd {
  float target_azimuth = 1;
  float target_elevation = 2;
}

message SafeModeExitCmd {
  bool force = 1;
}

message CommsDir {
  enum CommsMode {
    COMMS_MODE_FULL = 0;
    COMMS_MODE_SLOW = 1;
    COMMS_MODE_STOP = 2;
  }
  CommsMode mode = 1;
}

// Wrapper for all packet types transferred across WashU Satellite projects
message MessageEnvelope {
  // routing information
  string sender_id = 1;
  string dest_id = 2;

  // define all possible message bodies
  oneof message_body {
    airis.telemetry.v1.Beacon airis_beacon = 10;
    EstablishClient internal_establish_client = 11;
    Message internal_message = 12;
    airis.telemetry.v1.GCNAlert gcn_alert = 13;
    airis.telemetry.v1.LocalizationUpdate localization_update = 14;
    airis.telemetry.v1.NavigationUpdate navigation_update = 15;
    PointingCmd pointing_cmd = 16;
    SafeModeExitCmd safe_mode_exit_cmd = 17;
    airis.telemetry.v1.EventNotification event_notification = 18;
    airis.telemetry.v1.ImgData image_data = 19;
    CommsDir comms_directive = 20;
  }
}
